### PR TITLE
Concrete poly

### PR DESCRIPTION
**Pull request by stchang**

### CODE REVIEW

**Comment by stchang** [comment]
Because mutating a local variable is safe.

**Comment by AlexKnauth** [comment]
That's wrong. The `relations` hash isn't a mutable local variable, it's a "global" (almost) object. If our type system treats mutable objects as fine to mutate if they're bound to local variables, then that's unsound.

**Comment by stchang** [comment]
It's safe if no additional symbolic paths are introduced between the binding and use. Read my newest email.

**Comment by AlexKnauth** [comment]
A place where there are no symbolic paths introduced between "binding" of a local variable and the use:
```racket
#lang rosette
(define-symbolic a boolean?)

;; x : (CBoxof CInt)
(define x (box 0))

(if a
    (let ([y x])
      (set-box! y 1)) ; should not be allowed, y being a local var doesn't mean anything
    (void))

;; has type CInt, but value (ite a 1 0)
(unbox x)
```
It matters where the object was created (and the lifetime of it, in the Rust sense of the word), not where the local variable was bound.

**Comment by stchang** [comment]
Yes ok you're right. Data structures need to be handled more carefully.

**Comment by AlexKnauth** [comment]
I'll try adding a case in `lambda` for an expected type of `C→/•`, and after that I'll see if just using `C→/•` in those places helps.

**Comment by stchang** [comment]
Actually, in this case, the patch is ok because hashes are unlifted right? But you're right for the lifted structures it wont work.

**Comment by stchang** [comment]
Yes, just use `lambda/conc` and `C->/conc` and it should work. I'm trying the same thing in my fork.

**Pull request closed without merging**
